### ISSUE TITLE
Opening and closing databases?

### ISSUE THREAD

**Issue by coleifer** [pmwkaa/sophia#106]
Hi, I'm hoping you might be able to explain an error I saw when adding a test-case for my library. The test opens the DB, does a couple inserts, closes, re-opens and attempts to read. When I say "DB" I mean an actual database object, not the environment. Does it make sense / is it possible to close a database, or do you just close the environment?

I tried modifying the test to close the environment instead and ran into this error when attempting to re-open: 'sophia/environment/se_recover.c:94 database id 1 is not declared'.

This is because I did not re-declare the database before opening the environment. Is that necessary, then? The docs make it seem like there's no difference between opening the database along with the env, or doing so afterwards.

**Comment by pmwkaa** [comment]
**shutdown/drop**

Database shutdown is tricky. And i'm thinking to add explicit sp_close() to make it more clear:

```C
void *db = sp_getobject(env, "db.test");
sp_destroy(db); // unref
sp_destroy(db); // unref, final unref schedules shutdown
```

When we get our database object by sp_getobject() (like in example above), it will increment reference counter for the db. When we do sp_destroy() on database object for the first time, it will do unref. Second sp_destroy() call, will schedule database shutdown. Database close will not happen in instant, because there are possible transactions and compaction threads working with in in a moment. When final transaction is completed, database will be closed automatically by background worker. Additionally, there are transactional visibility for databases. Shutdown-await databases will result in an error in attempt to use them for a new transactions. Also, active transactions will not see a newly created database.

Exactly the same process is happened when we try to sp_drop() a database.

**database id and recover**

Sophia does not save configuration scheme for a databases at the moment, it should be redefined at start. When new database is created DSN (database seq number) is assigned. This number is used in log-records to match a database. On environment open, log files are replayed and if it can't find a database by id, it will result in a error you saw above. Also, it is not possible to open a database with data during an environment run (only create). Because it would require to reply log files, which are shared for all databases.

I hope my explanation makes sense :)

**Comment by coleifer** [comment]
Yes, I think so, thanks!
